### ISSUE TITLE
damage

### ISSUE THREAD

**Issue by Koljenka** [dieckie/DGE#1]
![yas](https://cloud.githubusercontent.com/assets/18630731/15579396/bfe2390a-2364-11e6-8030-09ab839039ec.PNG)
`public void schaden() {
        if(getX() == eichhoernchen.getX() && getY() == 100) {
            eichhoernchen.hurt(1);
        }
    }`

 der schaden fuktioniert blöd.

**Comment by dieckie** [comment]
asdf

**Comment by dieckie** [comment]
Voll gut gelöst!
