### ISSUE TITLE
Speichern

### ISSUE THREAD

**Issue by dieckie** [dieckie/DGE#2]
Häää, ihr Dooofies, das mit dem Speichern funktioniert garnicht richtig. Habt ihr euch das überhaupt mal angeguck?!!!!!!!!!!!!!!!!!!!111?

**Comment by dieckie** [comment]
HAHA, fertig

**Comment by dieckie** [comment]
Jaa, bei Neustart ohne vorherigen Launcher immer wieder von Vorne...

**Comment by Koljenka** [comment]
ahh du hast das extra geopend

**Comment by dieckie** [comment]
Wäre schön, wenn dus nochmal überprüfen könntest..

**Comment by dieckie** [comment]
Naja, nichts geändert
